# Generated by Django 6.0.4 on 2026-04-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='partner',
            new_name='make',
        ),
    ]
